name=Boardoza TMAG5170 3D Hall Sensor
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for Boardoza TMAG5170 3D Hall Sensor
paragraph=This library provides an easy‑to‑use API for interfacing with the Boardoza TMAG5170 high‑precision 3D linear Hall‑effect sensor breakout. It handles SPI communication, returns accurate magnetic field measurements along X, Y, and Z axes, and includes built‑in error checking, configurable measurement modes, and conversion utilities. With minimal dependencies and clear example sketches, it’s designed to help you integrate the TMAG5170 quickly into any Arduino or PlatformIO project.
category=Sensors
url=https://github.com/Boardoza/Boardoza_TMAG5170_3D_Hall_Sensor_Breakout_Board
architectures=*
